### 토큰 값 획득
GET {{url}}/token

> {%
client.test("Validate", function () {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.contentType.mimeType === "application/json", "Expected 'application/json'");
    client.assert(response.body.length > 0);
});

client.global.set("admin_jwt_token", response.body[1].jwtToken);
%}

### 1. 충전소 페이징, 정렬 검색
GET {{url}}/charge?name=test

> {%
 client.assert(response.status === 200, "status is not 200")
 %}

### 2. getChargeByChargePlaceId
GET {{url}}/charge/testId

> {%
    client.assert(response.status === 200, "status is not 200")
%}

### 3. addCharge
POST {{url}}/charge
Content-Type: application/json
Authorization: {{admin_jwt_token}}

{
  "chargePlaceId": "createTestChargePlaceId",
  "name": "createTestName",
  "totalCount": 10,
  "currentCount": 20,
  "chargeMembership": "MEMBERSHIP"
}

> {%
    client.assert(response.status === 201, "status is not 201")
%}

### 4. updateCharge
PATCH {{url}}/charge/createTestChargePlaceId
Content-Type: application/json
Authorization: {{admin_jwt_token}}

{
  "name": "updateTestName",
  "totalCount": 9,
  "currentCount": 4
}

> {%
    client.assert(response.status === 200, "status is not 200")
%}

### 5. deleteCharge
DELETE {{url}}/charge/createTestChargePlaceId
Content-Type: application/json
Authorization: {{admin_jwt_token}}

> {%
    client.assert(response.status === 204, "status is not 200")
%}
